export type Locale = "en" | "zh";

export const COPY: Record<Locale, Record<string, string>> = {
  en: {
    settings: "Settings",
    apiProvider: "API provider",
    provider: "Provider",
    apiKeys: "API keys",
    openaiKey: "OpenAI API key",
    saveKeys: "Save settings",
    saving: "Saving",
    openaiCompatible: "OpenAI-compatible",
    baseUrl: "Base URL",
    modelId: "Model ID",
    baseUrlNote: "Leave Base URL empty to use OpenAI directly. Fill it for OpenAI-compatible third-party gateways.",
    historyFilter: "History filter",
    allProviders: "All providers",
    allModels: "All models",
    create: "Create",
    promptStudio: "Prompt studio",
    textToImage: "Text to image",
    imageToImage: "Image to image",
    model: "Model",
    aspectRatio: "Aspect Ratio",
    resolution: "Resolution",
    quality: "Quality",
    fidelity: "Fidelity",
    prompt: "Prompt",
    singleMode: "Single",
    batchMode: "Batch",
    batchPrompts: "prompts",
    batchTemplate: "Template",
    promptPlaceholderText: "Describe the image you want to create...",
    promptPlaceholderImage: "Describe the change to make from the reference image...",
    batchPromptPlaceholderText: "---PROMPT---\nSubject: glass greenhouse\nScene: morning mist, soft sunlight, wet stone path\nStyle: cinematic product poster, rich detail\n---END---\n\n---PROMPT---\nSubject: silver roadster\nScene: dusk by the sea, low camera angle\nStyle: editorial automotive photo\n---END---",
    batchPromptPlaceholderImage: "---PROMPT---\nChange the background to winter sunlight.\nKeep the product shape unchanged.\nAdd a soft studio reflection.\n---END---\n\n---PROMPT---\nMake the image feel like an editorial magazine cover.\nPreserve the original subject and clean edges.\n---END---",
    clear: "Clear",
    quickStarts: "Quick starts",
    random: "Random",
    addReference: "Add reference",
    dragImages: "Drag images here for image-to-image",
    ready: "Ready",
    missingKey: "Missing API key",
    requestSent: "Request sent",
    generatingSmall: "image is being generated",
    backgroundRunning: "Task is running",
    stayInStudio: "Stay here",
    runInBackground: "Back to gallery",
    backgroundRunComplete: "Task completed. Gallery updated.",
    backgroundRunFailed: "Task failed. Check task monitor.",
    backgroundRunQueued: "Task is running in the background.",
    referencesEnabled: "references enabled when supported",
    generatingWith: "Generating with",
    generating: "Generating",
    generateImage: "Generate image",
    generateBatch: "Generate batch",
    generatingBatch: "Generating batch",
    result: "Result",
    imageOutput: "Image output",
    batchOutput: "Batch output",
    batchProgress: "Batch progress",
    batchElapsed: "Elapsed",
    batchEmpty: "Batch results will appear here.",
    batchQueued: "Queued",
    batchCreating: "Creating",
    batchPending: "Pending",
    batchPaused: "Paused",
    batchRunning: "Running",
    batchSucceeded: "Succeeded",
    batchFailed: "Failed",
    batchComplete: "Complete",
    batchRetry: "Retry",
    batchPause: "Pause",
    batchResume: "Resume",
    jobKill: "Kill",
    jobKillConfirm: "Force kill this task?",
    jobKillFailed: "Could not force kill task.",
    batchRetryAllFailed: "Retry failed",
    batchTimedOut: "Batch exceeded 10 minutes. Unfinished tasks were cleared as timed out.",
    batchTooManyPrompts: "Use 20 prompts or fewer.",
    batchPromptTooLong: "Each prompt must be 2000 characters or fewer.",
    batchFormatIncomplete: "Finish each prompt block with ---END---.",
    batchFormatOutsideText: "Remove text outside prompt blocks.",
    batchFormatEmptyBlock: "Prompt blocks cannot be empty.",
    providerReady: "Provider ready",
    generatingImage: "Generating image",
    keepOpen: "You can keep waiting here or return to the gallery.",
    noImageYet: "No image yet",
    emptyResult: "Choose a provider, enter a prompt, and generate your first image.",
    editThisImage: "Edit this image",
    copyLink: "Copy link",
    copied: "Copied",
    download: "Download",
    open: "Open",
    preview: "Preview",
    generationDetails: "Generation details",
    promptUsed: "Prompt",
    copyPrompt: "Copy prompt",
    history: "History",
    images: "images",
    historyEmpty: "Generated images will appear here.",
    loadMore: "Load more",
    loadingMore: "Loading",
    text: "Text",
    imageInput: "Image input",
    closePreview: "Close preview",
    imagePreview: "Image preview",
    language: "中文",
    languageTitle: "Switch to Chinese",
    configuredReplace: "Configured; enter a new key to replace",
    keySaved: "Saved. Provider settings were updated.",
    settingsLoadFailed: "Provider settings failed to load.",
    catalogLoadFailed: "Model catalog failed to load.",
    historyLoadFailed: "History failed to load.",
    chooseModelFirst: "Choose a model first.",
    providerNoKey: "This provider has no API key configured.",
    enterPrompt: "Enter a prompt.",
    imageNeedsReference: "Image-to-image needs an upload or a history image.",
    generationFailed: "Generation failed.",
    clearHistoryFailed: "History could not be cleared.",
    clearHistory: "Clear history",
    clearHistoryConfirm: "Clear all history images? This cannot be undone.",
    moreActions: "More actions",
    account: "Account",
    admin: "Admin",
    logout: "Log out",
    textReady: "Text ready",
    textOff: "Text off",
    imageReady: "Image ready",
    imageOff: "Image off",
    continueReady: "Continue ready",
    continueOff: "Continue off",
    editingFrom: "Editing from"
  },
  zh: {
    settings: "设置",
    apiProvider: "API 供应商",
    provider: "供应商",
    apiKeys: "API 密钥",
    openaiKey: "OpenAI API 密钥",
    saveKeys: "保存全部设置",
    saving: "保存中",
    openaiCompatible: "OpenAI 兼容接口",
    baseUrl: "Base URL",
    modelId: "模型 ID",
    baseUrlNote: "留空表示直连 OpenAI；填写后可使用 OpenAI 兼容的第三方网关。",
    historyFilter: "历史筛选",
    allProviders: "全部供应商",
    allModels: "全部模型",
    create: "创作",
    promptStudio: "提示词工作台",
    textToImage: "文生图",
    imageToImage: "图生图",
    model: "模型",
    aspectRatio: "宽高比",
    resolution: "分辨率",
    quality: "质量",
    fidelity: "保真度",
    prompt: "提示词",
    singleMode: "单张",
    batchMode: "批量",
    batchPrompts: "条提示词",
    batchTemplate: "模板",
    promptPlaceholderText: "描述你想生成的图片...",
    promptPlaceholderImage: "描述你想基于参考图做出的修改...",
    batchPromptPlaceholderText: "---PROMPT---\n主体：晨雾中的玻璃温室\n场景：柔和晨光、湿润石板路、空气有薄雾\n风格：电影感产品海报，细节丰富\n---END---\n\n---PROMPT---\n主体：海边黄昏的银色跑车\n场景：低机位、远处海平线、车身反射夕阳\n风格：高端汽车杂志大片\n---END---",
    batchPromptPlaceholderImage: "---PROMPT---\n把背景改成冬日阳光。\n保持主体形状不变。\n添加柔和的棚拍倒影。\n---END---\n\n---PROMPT---\n让画面更像杂志封面。\n保留原主体和干净边缘。\n---END---",
    clear: "清空",
    quickStarts: "快速示例",
    random: "随机",
    addReference: "添加参考图",
    dragImages: "拖拽图片到这里用于图生图",
    ready: "就绪",
    missingKey: "缺少 API 密钥",
    requestSent: "请求已发送",
    generatingSmall: "正在生成图片",
    referencesEnabled: "模型支持时可使用参考图",
    generatingWith: "正在使用",
    generating: "生成中",
    generateImage: "生成图片",
    generateBatch: "批量生成",
    generatingBatch: "批量生成中",
    result: "结果",
    imageOutput: "图片输出",
    batchOutput: "批量输出",
    batchProgress: "批量进度",
    batchElapsed: "耗时",
    batchEmpty: "批量结果会显示在这里。",
    batchQueued: "排队中",
    batchCreating: "创建中",
    batchPending: "等待中",
    batchRunning: "运行中",
    batchSucceeded: "已完成",
    batchFailed: "失败",
    batchComplete: "已结束",
    batchRetry: "重试",
    batchPause: "暂停",
    batchResume: "继续",
    jobKill: "强杀",
    jobKillConfirm: "确定强行杀除这个任务吗？",
    jobKillFailed: "强行杀除任务失败。",
    batchRetryAllFailed: "重试失败项",
    batchTimedOut: "批次超过 10 分钟，未完成任务已按超时失败清理。",
    batchTooManyPrompts: "最多输入 20 条提示词。",
    batchPromptTooLong: "每条提示词不能超过 2000 字符。",
    batchFormatIncomplete: "每个提示词块都需要用 ---END--- 结束。",
    batchFormatOutsideText: "请删除提示词块外的多余文本。",
    batchFormatEmptyBlock: "提示词块不能为空。",
    providerReady: "供应商已就绪",
    generatingImage: "正在生成图片",
    keepOpen: "可以在这里等待，也可以返回图库。",
    noImageYet: "还没有图片",
    emptyResult: "选择供应商，输入提示词，然后生成第一张图片。",
    editThisImage: "编辑此图",
    copyLink: "复制链接",
    copied: "已复制",
    download: "下载",
    open: "打开",
    preview: "预览",
    generationDetails: "生成详情",
    promptUsed: "提示词",
    copyPrompt: "复制提示词",
    history: "历史",
    images: "张图片",
    historyEmpty: "生成后的图片会显示在这里。",
    loadMore: "加载更多",
    loadingMore: "加载中",
    text: "文本",
    imageInput: "图片输入",
    closePreview: "关闭预览",
    imagePreview: "图片预览",
    language: "EN",
    languageTitle: "切换到英文",
    configuredReplace: "已配置；输入新密钥可替换",
    keySaved: "已保存，供应商设置已更新。",
    settingsLoadFailed: "供应商设置加载失败。",
    catalogLoadFailed: "模型目录加载失败。",
    historyLoadFailed: "历史记录加载失败。",
    chooseModelFirst: "请先选择模型。",
    providerNoKey: "当前供应商尚未配置 API 密钥。",
    enterPrompt: "请输入提示词。",
    imageNeedsReference: "图生图需要上传参考图或选择历史图片。",
    generationFailed: "生成失败。",
    clearHistoryFailed: "历史记录清空失败。",
    clearHistory: "清空历史",
    clearHistoryConfirm: "确定清空所有历史图片吗？此操作不可撤销。",
    moreActions: "更多操作",
    account: "账号",
    admin: "管理",
    logout: "退出登录",
    backgroundRunning: "任务正在运行",
    stayInStudio: "留在生图台",
    runInBackground: "返回图库后台运行",
    backgroundRunComplete: "任务已完成，图库已更新。",
    backgroundRunFailed: "任务失败，请查看任务监控。",
    backgroundRunQueued: "任务已在后台运行。",
    textReady: "支持文生图",
    textOff: "不支持文生图",
    imageReady: "支持图生图",
    imageOff: "不支持图生图",
    continueReady: "支持继续编辑",
    continueOff: "不支持继续编辑",
    editingFrom: "正在编辑来源"
  }
};

export function getCopy(locale: Locale, key: string) {
  return COPY[locale][key] ?? COPY.en[key] ?? key;
}
